//! JavaScript parity gate: extract the `sample` JS corpus with `habitat-graph` and compare
//! against the committed golden, per relation.
//!
//! The golden (`tests/fixtures/goldens/js/graph.json`) was generated by the
//! `gen_golden_js` example using the same JS extractor and pinned as the authoritative
//! reference for regression detection.  Because we are the first and only JS extractor
//! (no external Python oracle exists for JS), the golden encodes our own committed output —
//! any drop is OUR regression; any rise means the extractor improved and should be ratcheted.
//!
//! Coverage design:
//!   - 20 nodes: file, 4 standalone fns/arrows, 3 classes + their 12 methods.
//!   - 20 structural edges: 7 `contains` + 12 `method` + 1 `inherits` (local Animal→Dog).
//!   - 0 `imports_from`/`calls`/`uses` in the golden — external import targets (events,
//!     fs/promises, path) and external bases (EventEmitter) are never nodes in a
//!     single-file corpus, so `assemble` drops those dangling edges (documented policy).
//!
//! Per the parity strategy (`ai_docs/06_PARITY_INTEL`): structural relations
//! (`contains` / `method` / `inherits` / `imports_from`) are expected to be well-covered;
//! `calls` / `uses` are deliberately NOT emitted, reported as documented divergence.

use std::path::PathBuf;

use habitat_graph_fixtures::{classify, from_core, from_golden};

/// Pinned-oracle baseline (LS-3): verified-good JS coverage. Any drop is OUR regression.
/// Ratchet UP when extraction legitimately improves.
///
/// 20/20 nodes (100%): all locally-defined symbols fully covered.
const JS_NODE_BASELINE: usize = 20;

/// 20/20 structural edges (100%): all contains + method + inherits edges covered.
/// External import/inherits edges are dangling and are not structural regressions
/// when only a single-file corpus is used.
const JS_STRUCT_BASELINE: usize = 20;

fn js_dir() -> PathBuf {
    PathBuf::from(format!(
        "{}/../../tests/fixtures/goldens/js",
        env!("CARGO_MANIFEST_DIR")
    ))
}

// ── 1. Primary parity gate ────────────────────────────────────────────────────────────────────

#[test]
fn js_structural_parity() {
    let dir = js_dir();

    // Our extraction: detect → extract → assemble → normalize.
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect .js files");
    assert!(!files.is_empty(), "must find at least one JS file under goldens/js/raw");

    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);

    // Golden (our committed reference — see module-level docs).
    let golden_json =
        std::fs::read_to_string(dir.join("graph.json")).expect("read js golden graph.json");
    let golden = from_golden(&golden_json).expect("parse js golden");

    let report = classify(&ours, &golden);

    let node_total = golden.nodes.len().max(1);
    let node_pct = (report.nodes_matched * 100 + node_total / 2) / node_total;
    eprintln!("\n=== JS sample parity ===");
    eprintln!(
        "NODES: {}/{} golden ids covered ({node_pct}%), {} extra",
        report.nodes_matched,
        golden.nodes.len(),
        report.nodes_extra.len()
    );

    eprintln!("EDGES by relation (matched / golden / ours):");
    let mut structural_matched = 0_usize;
    let mut structural_total = 0_usize;
    for rel in [
        "contains",
        "method",
        "inherits",
        "imports_from",
        "calls",
        "uses",
    ] {
        let g = golden.edges_with_relation(rel);
        let o = ours.edges_with_relation(rel);
        let matched = g.intersection(&o).count();
        eprintln!("  {rel:>12}: {matched} / {} / {}", g.len(), o.len());
        if matches!(rel, "contains" | "method" | "inherits" | "imports_from") {
            structural_matched += matched;
            structural_total += g.len();
        }
    }
    let struct_total = structural_total.max(1);
    let struct_pct = (structural_matched * 100 + struct_total / 2) / struct_total;
    eprintln!("STRUCTURAL coverage: {structural_matched}/{structural_total} ({struct_pct}%)\n");

    if !report.nodes_missing.is_empty() {
        eprintln!("MISSING NODES: {:?}", report.nodes_missing);
    }
    if !report.edges_missing.is_empty() {
        eprintln!("MISSING EDGES: {:?}", report.edges_missing);
    }

    // Regression gate (LS-3): assert against the PINNED-ORACLE BASELINE, not a loose floor.
    // The golden is pinned, so any drop in coverage is OUR regression. Ratchet UP on improvement.
    assert!(
        report.nodes_matched >= JS_NODE_BASELINE,
        "node coverage REGRESSED: {}/{} ({node_pct}%) < pinned baseline {JS_NODE_BASELINE} — \
         reconcile or ratchet",
        report.nodes_matched,
        golden.nodes.len()
    );
    assert!(
        structural_matched >= JS_STRUCT_BASELINE,
        "structural coverage REGRESSED: {structural_matched}/{structural_total} ({struct_pct}%) \
         < pinned baseline {JS_STRUCT_BASELINE} (LS-3)"
    );
}

// ── 2. Golden sanity: known node ids ─────────────────────────────────────────────────────────

#[test]
fn js_golden_has_file_node() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    assert!(
        g.nodes.contains("sample"),
        "golden must contain file node 'sample'"
    );
}

#[test]
fn js_golden_has_all_three_class_nodes() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    for expected in ["sample_animal", "sample_dog", "sample_eventbus"] {
        assert!(
            g.nodes.contains(expected),
            "golden must contain class node '{expected}'; got {g:?}",
            g = g.nodes
        );
    }
}

#[test]
fn js_golden_has_standalone_function_and_arrow_nodes() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    for expected in [
        "sample_createid",
        "sample_validatename",
        "sample_formatdate",
        "sample_parsequery",
    ] {
        assert!(
            g.nodes.contains(expected),
            "golden must contain fn node '{expected}'"
        );
    }
}

#[test]
fn js_golden_has_dog_method_nodes() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    for expected in [
        "sample_dog_constructor",
        "sample_dog_speak",
        "sample_dog_fetch",
        "sample_dog_validate",
    ] {
        assert!(
            g.nodes.contains(expected),
            "golden must contain Dog method node '{expected}'"
        );
    }
}

#[test]
fn js_golden_has_eventbus_method_nodes() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    for expected in [
        "sample_eventbus_constructor",
        "sample_eventbus_subscribe",
        "sample_eventbus_publish",
        "sample_eventbus_unsubscribe",
    ] {
        assert!(
            g.nodes.contains(expected),
            "golden must contain EventBus method node '{expected}'"
        );
    }
}

#[test]
fn js_golden_node_count_is_twenty() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    assert_eq!(
        g.nodes.len(),
        20,
        "golden must have exactly 20 unique node ids; got {}",
        g.nodes.len()
    );
}

#[test]
fn js_golden_edge_count_is_twenty() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    assert_eq!(
        g.edges.len(),
        20,
        "golden must have exactly 20 unique (source,target,relation) tuples; got {}",
        g.edges.len()
    );
}

// ── 3. Golden sanity: known edge tuples ──────────────────────────────────────────────────────

#[test]
fn js_golden_has_local_inherits_edge_animal_to_dog() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let edge = (
        "sample_animal".to_owned(),
        "sample_dog".to_owned(),
        "inherits".to_owned(),
    );
    assert!(
        g.edges.contains(&edge),
        "golden must have inherits edge (sample_animal, sample_dog)"
    );
}

#[test]
fn js_golden_has_contains_edge_file_to_animal() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let edge = (
        "sample".to_owned(),
        "sample_animal".to_owned(),
        "contains".to_owned(),
    );
    assert!(g.edges.contains(&edge), "golden must have contains edge (sample, sample_animal)");
}

#[test]
fn js_golden_has_method_edge_dog_to_speak() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let edge = (
        "sample_dog".to_owned(),
        "sample_dog_speak".to_owned(),
        "method".to_owned(),
    );
    assert!(g.edges.contains(&edge), "golden must have method edge (sample_dog, sample_dog_speak)");
}

#[test]
fn js_golden_has_twelve_method_edges() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let methods = g.edges_with_relation("method");
    assert_eq!(
        methods.len(),
        12,
        "golden must have exactly 12 method edges; got {}",
        methods.len()
    );
}

#[test]
fn js_golden_has_seven_contains_edges() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let contains_edges = g.edges_with_relation("contains");
    assert_eq!(
        contains_edges.len(),
        7,
        "golden must have exactly 7 contains edges; got {}",
        contains_edges.len()
    );
}

#[test]
fn js_golden_has_one_inherits_edge() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    let inherits = g.edges_with_relation("inherits");
    assert_eq!(
        inherits.len(),
        1,
        "golden must have exactly 1 inherits edge (Animal→Dog, local); external \
         EventEmitter base is dangling and dropped by assemble"
    );
}

#[test]
fn js_golden_has_no_calls_or_uses_or_imports_from_edges() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g = from_golden(&json).expect("parse golden");
    for forbidden in ["calls", "uses", "imports_from"] {
        let count = g.edges_with_relation(forbidden).len();
        assert_eq!(
            count, 0,
            "golden must have 0 '{forbidden}' edges; got {count} \
             (imports_from targets are external and dropped by assemble)"
        );
    }
}

// ── 4. Extraction assertions: our output matches known invariants ──────────────────────────

#[test]
fn our_extraction_finds_twenty_nodes() {
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    assert_eq!(
        ours.nodes.len(),
        20,
        "our extractor must produce exactly 20 nodes from sample.js; got {}",
        ours.nodes.len()
    );
}

#[test]
fn our_extraction_finds_private_method_validate() {
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    assert!(
        ours.nodes.contains("sample_dog_validate"),
        "private method #validate must appear as sample_dog_validate (# stripped)"
    );
}

#[test]
fn our_extraction_finds_static_method_create() {
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    assert!(
        ours.nodes.contains("sample_animal_create"),
        "static method 'create' must appear as sample_animal_create"
    );
}

#[test]
fn our_extraction_finds_local_inherits_edge() {
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    let edge = (
        "sample_animal".to_owned(),
        "sample_dog".to_owned(),
        "inherits".to_owned(),
    );
    assert!(
        ours.edges.contains(&edge),
        "local inherits edge (sample_animal → sample_dog) must survive assembly"
    );
}

#[test]
fn our_extraction_drops_external_inherits_edge() {
    // EventEmitter is not a node in the graph → the inherits edge is a dangling edge and
    // must be dropped by assemble (documented policy).
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    assert!(
        !ours.nodes.contains("eventemitter"),
        "external base 'eventemitter' must NOT appear as a node"
    );
    let external_inherits = ours
        .edges
        .iter()
        .any(|(src, _, rel)| src == "eventemitter" && rel == "inherits");
    assert!(
        !external_inherits,
        "external inherits edge (eventemitter → sample_eventbus) must be dropped by assemble"
    );
}

#[test]
fn our_extraction_emits_no_calls_or_uses_edges() {
    let dir = js_dir();
    let files =
        habitat_graph_source::detect(&dir.join("raw"), &["js"]).expect("detect");
    let extractions = habitat_graph_extract::extract_files(&files).expect("extract");
    let graph = habitat_graph_build::assemble(extractions);
    let ours = from_core(&graph);
    for forbidden in ["calls", "uses"] {
        let count = ours.edges_with_relation(forbidden).len();
        assert_eq!(count, 0, "'{forbidden}' edges must never be emitted");
    }
}

#[test]
fn js_golden_parses_without_error() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    assert!(
        from_golden(&json).is_ok(),
        "js golden must parse cleanly"
    );
}

#[test]
fn js_golden_node_set_is_deterministic() {
    let dir = js_dir();
    let json = std::fs::read_to_string(dir.join("graph.json")).expect("read golden");
    let g1 = from_golden(&json).expect("first parse");
    let g2 = from_golden(&json).expect("second parse");
    assert_eq!(g1.nodes, g2.nodes, "node set must be deterministic");
    assert_eq!(g1.edges, g2.edges, "edge set must be deterministic");
}
